// SPDX-FileCopyrightText: 2026 Mohamed Hammad & Spacecraft Software
// SPDX-License-Identifier: GPL-3.0-or-later
//! Putting engram's commands in front of the user, inside each harness.
//!
//! Engram has been registered as an MCP server in every harness on a typical
//! developer's machine for a while. What was missing was a *command surface*:
//! no `/engram-save-chat`, no way to invoke engram by name from inside a
//! session. This module writes the command files that close that gap.
//!
//! # Three rules
//!
//! 1. **One source of truth.** Command bodies live in `plugins/engram/` and
//!    are embedded with [`include_str!`], so the plugin directory and the
//!    installed files cannot drift, and the compiler enforces they exist.
//! 2. **Only files engram owns.** Every target is written under
//!    [`WritePolicy::Owned`] with a generated-by banner. A file without that
//!    banner was written by the user and is skipped unless `--force`. Nothing
//!    here splices into a foreign file, and nothing here deletes.
//! 3. **Never conjure a harness.** Only *detected* harnesses are written to.
//!    Engram will not `mkdir ~/.qwen` for a Qwen that is not installed.
//!
//! # Why this is CLI-only
//!
//! This writes into `$HOME`, one step beyond anything else engram does —
//! `rule sync` stays inside the project root. The HTTP surface has no auth
//! and binds to localhost, which already means any local process can rewrite
//! a project's `AGENTS.md`. An HTTP `install` would extend that to the user's
//! home directory and, once hooks land, to code executed at every session
//! end. There is no route, and there should not be one.

use crate::harness::{self, HarnessSpec};
use crate::managed_file::{self, ManagedFile, WritePolicy};
use serde::Serialize;
use std::path::PathBuf;

/// One command engram installs, with its body embedded from the plugin
/// directory that is its single source of truth.
struct CommandTemplate {
    /// Short name, substituted into [`HarnessSpec::command_file`].
    name: &'static str,
    body: &'static str,
}

const COMMANDS: &[CommandTemplate] = &[
    CommandTemplate {
        name: "save-chat",
        body: include_str!("../plugins/engram/commands/save-chat.md"),
    },
    CommandTemplate {
        name: "ingest",
        body: include_str!("../plugins/engram/commands/ingest.md"),
    },
    CommandTemplate {
        name: "context",
        body: include_str!("../plugins/engram/commands/context.md"),
    },
];

/// Marks a file as engram's to overwrite. A command file without this line
/// was written by someone else and is left alone.
///
/// The version is deliberately *not* in the banner: it would make every
/// release rewrite every file, turning `install` from idempotent into
/// perpetually-updating.
const BANNER: &str = "<!-- Generated by `engram install`. Edits are overwritten. -->";

/// What one harness got.
#[derive(Debug, Serialize)]
pub struct HarnessInstall {
    pub harness: &'static str,
    pub present: bool,
    /// The database baked into this harness's generated commands.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub db: Option<String>,
    pub files: Vec<ManagedFile>,
    /// Why nothing was written, when nothing was.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<&'static str>,
    /// Set when the harness's command directory is managed declaratively and
    /// engram's writes will not survive.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub warning: Option<String>,
}

/// The whole `engram install` payload.
#[derive(Debug, Serialize)]
pub struct InstallResult {
    pub dry_run: bool,
    pub harnesses: Vec<HarnessInstall>,
    pub installed: usize,
    pub skipped: usize,
    /// Present only when `--hooks` was passed. Absent — not empty — otherwise,
    /// so the payload shows at a glance that no settings file was considered.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub hooks: Vec<HookInstall>,
}

/// Renders one command file for one harness.
///
/// Two substitutions and no template engine: `{{DB}}` and `{{HARNESS}}`.
/// A harness that does not read YAML frontmatter (Codex prompts) has it
/// stripped, because it would otherwise render as literal text at the top of
/// every prompt.
pub fn render_command(template_body: &str, spec: &HarnessSpec, db: &str) -> String {
    let body = if spec.command_frontmatter {
        template_body.to_string()
    } else {
        strip_frontmatter(template_body)
    };
    let body = body.replace("{{DB}}", db).replace("{{HARNESS}}", spec.name);
    format!("{BANNER}\n{body}")
}

/// Removes a leading `---`-delimited YAML block.
fn strip_frontmatter(body: &str) -> String {
    let Some(rest) = body.strip_prefix("---\n") else {
        return body.to_string();
    };
    match rest.find("\n---\n") {
        Some(end) => rest[end + 5..].trim_start().to_string(),
        None => body.to_string(),
    }
}

/// True when the file may be overwritten: engram wrote it, or it does not
/// exist yet.
fn is_ours(path: &std::path::Path) -> bool {
    match std::fs::read_to_string(path) {
        Ok(text) => text.contains(BANNER),
        // Unreadable or absent: `write_managed` reports what happens next.
        Err(_) => true,
    }
}

/// True when the path resolves into the Nix store, i.e. a home-manager
/// symlink that engram cannot write and whose contents a rebuild would
/// replace anyway.
fn is_nix_managed(path: &std::path::Path) -> bool {
    // Walk up: the leaf usually does not exist yet, but its parent may
    // already be the store symlink.
    path.ancestors()
        .filter_map(|p| std::fs::read_link(p).ok())
        .any(|target| target.starts_with("/nix/store"))
}

/// Installs into the given harnesses.
///
/// # Errors
///
/// Returns the first write failure. Detection problems are reported per
/// harness rather than raised, so one unwritable harness does not abort the
/// rest.
pub fn install(
    targets: &[&'static HarnessSpec],
    db_override: Option<&str>,
    force: bool,
    dry_run: bool,
    hooks: bool,
) -> std::io::Result<InstallResult> {
    let mut harnesses = Vec::new();
    let mut hook_results = Vec::new();
    let mut installed = 0usize;
    let mut skipped = 0usize;

    for spec in targets {
        let detected = harness::describe(spec);
        let Some(dir) = harness::commands_dir(spec) else {
            harnesses.push(HarnessInstall {
                harness: spec.name,
                present: detected.present,
                db: None,
                files: Vec::new(),
                note: Some("no command surface engram can write"),
                warning: None,
            });
            continue;
        };
        if !detected.present {
            harnesses.push(HarnessInstall {
                harness: spec.name,
                present: false,
                db: None,
                files: Vec::new(),
                note: Some("not installed; engram will not create a home for it"),
                warning: None,
            });
            continue;
        }

        // The database the harness itself registered wins: it is the one the
        // user's agents actually share.
        let db = db_override
            .map(str::to_string)
            .or_else(|| harness::registered_db(spec).map(|p| p.to_string_lossy().into_owned()))
            .or_else(|| std::env::var("ENGRAM_DB").ok())
            .unwrap_or_else(|| "engram.db".to_string());

        let warning = is_nix_managed(&dir).then(|| {
            format!(
                "{} resolves into the Nix store; anything written here will be replaced by the \
                 next home-manager switch. Reference plugins/engram/ from your configuration \
                 instead.",
                dir.display()
            )
        });

        let mut files = Vec::new();
        for command in COMMANDS {
            let path = dir.join(spec.command_file.replace("{name}", command.name));
            if !force && !is_ours(&path) {
                skipped += 1;
                files.push(ManagedFile {
                    path: path.to_string_lossy().into_owned(),
                    outcome: managed_file::FileOutcome::Unchanged,
                    dry_run,
                    reason: Some("not generated by engram; pass --force to overwrite".to_string()),
                });
                continue;
            }
            let body = render_command(command.body, spec, &db);
            let written = managed_file::write_managed(&path, &body, WritePolicy::Owned, dry_run)?;
            if written.outcome != managed_file::FileOutcome::Unchanged {
                installed += 1;
            }
            files.push(written);
        }

        // Hooks are opt-in twice over: this flag, and the fact that a hook
        // only ever runs `ingest`.
        if hooks {
            match install_hooks(spec, &db, dry_run)? {
                Some(result) => hook_results.push(result),
                None => hook_results.push(HookInstall {
                    harness: spec.name,
                    path: String::new(),
                    outcome: managed_file::FileOutcome::Unchanged,
                    dry_run,
                    fragment: serde_json::Value::Null,
                    backup: None,
                    note: Some("this harness has no hook system engram can write"),
                }),
            }
        }

        harnesses.push(HarnessInstall {
            harness: spec.name,
            present: true,
            db: Some(db),
            files,
            note: None,
            warning,
        });
    }

    Ok(InstallResult {
        dry_run,
        harnesses,
        installed,
        skipped,
        hooks: hook_results,
    })
}

/// How long a hook may run before the harness gives up on it, in seconds.
/// Ingest streams a transcript and does one transaction; 30 seconds is
/// generous for that and short enough not to stall session teardown.
const HOOK_TIMEOUT_SECS: u64 = 30;

/// What `--hooks` did to a harness's settings file.
#[derive(Debug, Serialize)]
pub struct HookInstall {
    pub harness: &'static str,
    pub path: String,
    pub outcome: managed_file::FileOutcome,
    pub dry_run: bool,
    /// The exact fragment merged in, so `--dry-run` shows precisely what
    /// would change rather than describing it.
    pub fragment: serde_json::Value,
    /// Where the previous settings file was copied before being rewritten.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub backup: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub note: Option<&'static str>,
}

/// The SessionEnd entry engram installs.
///
/// **`ingest`, never `save-chat`.** Capturing into the database is invisible
/// and reversible; writing a `.texi` into someone's repository at the end of
/// every session, unasked, is not. The archive stays a thing the user asks
/// for.
fn hook_fragment(db: &str) -> serde_json::Value {
    serde_json::json!({
        "hooks": [{
            "type": "command",
            "command": format!("engram --db {db} ingest --harness claude-code --session latest"),
            "timeout": HOOK_TIMEOUT_SECS,
        }]
    })
}

/// True when this SessionEnd entry is one engram wrote.
///
/// Matched on the command text rather than a marker key, because the settings
/// schema has no room for one. Narrow enough not to claim a user's own
/// engram-adjacent hook: it must invoke `engram` *and* `ingest`.
fn is_engram_hook(entry: &serde_json::Value) -> bool {
    entry
        .get("hooks")
        .and_then(|h| h.as_array())
        .is_some_and(|hooks| {
            hooks.iter().any(|h| {
                h.get("command")
                    .and_then(|c| c.as_str())
                    .is_some_and(|c| c.contains("engram") && c.contains(" ingest"))
            })
        })
}

/// Merges the SessionEnd hook into a harness's settings file.
///
/// Additive and surgical: only `/hooks/SessionEnd` is touched, engram's own
/// entry is replaced in place if present, and **other people's SessionEnd
/// hooks are left exactly where they are** — the field is an array, and
/// several hooks on one event is a legitimate configuration, not a conflict
/// to refuse.
///
/// The file's key order survives because `serde_json` is compiled with
/// `preserve_order`; without it engram would silently alphabetize a config it
/// does not own. A timestamped backup is written before any change, because
/// this is the one place engram rewrites a structured file a user hand-edits.
///
/// # Errors
///
/// Returns an error if the settings file exists but cannot be read or parsed,
/// or if the write fails. A malformed settings file is *not* overwritten —
/// engram refuses rather than replacing something it could not understand.
pub fn install_hooks(
    spec: &'static HarnessSpec,
    db: &str,
    dry_run: bool,
) -> std::io::Result<Option<HookInstall>> {
    let Some(relative) = spec.hooks_config else {
        return Ok(None);
    };
    let Some(path) = harness::in_home(relative) else {
        return Ok(None);
    };

    let existing = match std::fs::read_to_string(&path) {
        Ok(s) => Some(s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => return Err(e),
    };

    let mut settings: serde_json::Value = match existing.as_deref() {
        None => serde_json::json!({}),
        Some(text) if text.trim().is_empty() => serde_json::json!({}),
        Some(text) => serde_json::from_str(text).map_err(|e| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "{} is not valid JSON ({e}); engram will not overwrite a settings file it \
                     cannot parse",
                    path.display()
                ),
            )
        })?,
    };

    let fragment = hook_fragment(db);

    // Navigate/create `hooks.SessionEnd`, leaving every sibling untouched.
    let hooks = settings
        .as_object_mut()
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("{} is JSON but not an object", path.display()),
            )
        })?
        .entry("hooks")
        .or_insert_with(|| serde_json::json!({}));
    let session_end = hooks
        .as_object_mut()
        .ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("{}: `hooks` is not an object", path.display()),
            )
        })?
        .entry("SessionEnd")
        .or_insert_with(|| serde_json::json!([]));
    let entries = session_end.as_array_mut().ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("{}: `hooks.SessionEnd` is not an array", path.display()),
        )
    })?;

    match entries.iter_mut().find(|e| is_engram_hook(e)) {
        Some(mine) => *mine = fragment.clone(),
        None => entries.push(fragment.clone()),
    }

    let next = format!("{}\n", serde_json::to_string_pretty(&settings)?);
    let outcome = match existing.as_deref() {
        None => managed_file::FileOutcome::Created,
        Some(current) if current == next => managed_file::FileOutcome::Unchanged,
        Some(_) => managed_file::FileOutcome::Updated,
    };

    let mut backup = None;
    if outcome != managed_file::FileOutcome::Unchanged && !dry_run {
        if let Some(current) = existing.as_deref() {
            // One backup per write, stamped, so a bad merge is always
            // recoverable and an earlier backup is never clobbered.
            let stamp = crate::time::now_iso8601().replace(':', "-");
            let backup_path = path.with_extension(format!("json.engram-backup-{stamp}"));
            std::fs::write(&backup_path, current)?;
            backup = Some(backup_path.to_string_lossy().into_owned());
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, &next)?;
    }

    Ok(Some(HookInstall {
        harness: spec.name,
        path: path.to_string_lossy().into_owned(),
        outcome,
        dry_run,
        fragment,
        backup,
        note: None,
    }))
}

/// Harnesses `install` writes to when none is named: every detected one that
/// has a command surface.
pub fn default_targets() -> Vec<&'static HarnessSpec> {
    harness::ALL
        .iter()
        .filter(|s| s.commands_dir.is_some())
        .collect()
}

/// Absolute path of the plugin directory shipped with the source tree, for
/// the `--list` report.
pub fn plugin_dir_hint() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("plugins/engram")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn claude() -> &'static HarnessSpec {
        harness::spec(harness::Harness::ClaudeCode)
    }

    fn codex() -> &'static HarnessSpec {
        harness::spec(harness::Harness::Codex)
    }

    /// Every embedded template must still be a well-formed command file. This
    /// is what makes `include_str!` an anti-drift mechanism rather than just
    /// a way to avoid a second copy.
    #[test]
    fn every_template_is_well_formed() {
        assert!(!COMMANDS.is_empty());
        for command in COMMANDS {
            assert!(
                command.body.starts_with("---\n"),
                "{}: missing frontmatter",
                command.name
            );
            assert!(
                command.body.contains("description:"),
                "{}: frontmatter has no description",
                command.name
            );
            assert!(
                command.body.contains("{{DB}}"),
                "{}: must pin the database explicitly, or it writes to the wrong store",
                command.name
            );
        }
    }

    #[test]
    fn render_substitutes_both_placeholders_and_banners_the_file() {
        let out = render_command(COMMANDS[0].body, claude(), "/shared/engram.db");
        assert!(out.starts_with(BANNER));
        assert!(out.contains("--db /shared/engram.db"));
        assert!(out.contains("--harness claude-code"));
        assert!(!out.contains("{{DB}}"));
        assert!(!out.contains("{{HARNESS}}"));
        // Claude Code reads frontmatter, so it survives.
        assert!(out.contains("description:"));
    }

    #[test]
    fn frontmatter_is_stripped_for_harnesses_that_do_not_read_it() {
        let out = render_command(COMMANDS[0].body, codex(), "/shared/engram.db");
        assert!(out.starts_with(BANNER));
        assert!(
            !out.contains("argument-hint:"),
            "codex prompts would render frontmatter as literal text: {out}"
        );
        // The body itself still arrives.
        assert!(out.contains("engram"));
        assert!(out.contains("--db /shared/engram.db"));
    }

    #[test]
    fn strip_frontmatter_leaves_bodies_without_it_alone() {
        assert_eq!(
            strip_frontmatter("no frontmatter here"),
            "no frontmatter here"
        );
        assert_eq!(strip_frontmatter("---\na: b\n---\nbody\n"), "body\n");
        // Unterminated block: leave it rather than eat the whole file.
        assert_eq!(strip_frontmatter("---\ndangling"), "---\ndangling");
    }

    /// The banner carries no version, so a release does not rewrite every
    /// installed file.
    #[test]
    fn render_is_stable_across_calls() {
        let a = render_command(COMMANDS[0].body, claude(), "/db");
        let b = render_command(COMMANDS[0].body, claude(), "/db");
        assert_eq!(a, b);
        assert!(!BANNER.contains(env!("CARGO_PKG_VERSION")));
    }

    /// The plugin manifest and the crate must not drift apart.
    #[test]
    fn plugin_manifest_version_matches_the_crate() {
        let manifest = include_str!("../plugins/engram/.claude-plugin/plugin.json");
        let value: serde_json::Value =
            serde_json::from_str(manifest).expect("plugin.json is valid JSON");
        assert_eq!(
            value["version"].as_str().expect("version"),
            env!("CARGO_PKG_VERSION"),
            "plugins/engram/.claude-plugin/plugin.json is out of date"
        );
        assert_eq!(value["name"], "engram");
    }

    #[test]
    fn default_targets_are_exactly_the_harnesses_with_a_command_surface() {
        let targets = default_targets();
        assert!(!targets.is_empty());
        for spec in &targets {
            assert!(spec.commands_dir.is_some());
        }
        // Harnesses with no command surface are excluded, not silently
        // pretended to work.
        assert!(!targets
            .iter()
            .any(|s| s.id == harness::Harness::Antigravity));
    }
}

// Rust guideline compliant 2026-05-18
